"""
Simple UI dashboard for visualizing alerts generated by the
Secure Cloud-Enabled Network Monitoring System.

This dashboard:
- Reads alerts from alerts.txt
- Displays alert statistics
- Shows severity distribution
- Refreshes automatically for live monitoring simulation
"""

import streamlit as st
import pandas as pd
import time
from pathlib import Path

ALERT_FILE = "output/alerts.txt"


# -------------------------------------------------
# Function: Read alerts from file
# -------------------------------------------------
def load_alerts():
    alerts = []

    file_path = Path(ALERT_FILE)

    if not file_path.exists():
        return pd.DataFrame(columns=["timestamp", "severity", "message"])

    with open(ALERT_FILE, "r") as file:
        lines = file.readlines()

    for line in lines:
        try:
            # Expected format:
            # [HIGH] 2026-04-20 10:10:10 - Port scan detected

            severity_end = line.find("]")
            severity = line[1:severity_end]

            remaining = line[severity_end + 2:].strip()

            timestamp, message = remaining.split(" - ", 1)

            alerts.append({
                "timestamp": timestamp,
                "severity": severity,
                "message": message
            })

        except Exception:
            continue

    return pd.DataFrame(alerts)


# -------------------------------------------------
# Streamlit UI
# -------------------------------------------------
st.set_page_config(
    page_title="Secure Network Monitor",
    layout="wide"
)

st.title("Secure Cloud Network Monitoring Dashboard")
st.markdown("Real-time monitoring and threat visualization")

# Auto refresh
refresh = st.sidebar.checkbox("Enable Auto Refresh", value=False)

if refresh:
    time.sleep(30)
    st.rerun()

# Load data
alerts_df = load_alerts()

# Metrics
col1, col2, col3 = st.columns(3)

with col1:
    st.metric("Total Alerts", len(alerts_df))

with col2:
    high_count = len(alerts_df[alerts_df["severity"] == "HIGH"])
    st.metric("High Severity", high_count)

with col3:
    medium_count = len(alerts_df[alerts_df["severity"] == "MEDIUM"])
    st.metric("Medium Severity", medium_count)

st.divider()

left_col, right_col = st.columns(2)

# -------------------------------------------------
# Left Side - Severity Chart
# -------------------------------------------------
with left_col:
    st.subheader("Severity Distribution")

    if not alerts_df.empty:
        severity_counts = alerts_df["severity"].value_counts()
        st.bar_chart(severity_counts)
    else:
        st.warning("No alerts available.")

# -------------------------------------------------
# Right Side - Recent Alerts
# -------------------------------------------------
with right_col:
    st.subheader("Recent Alerts")

    if not alerts_df.empty:
        st.dataframe(alerts_df, use_container_width=True, height=350)
    else:
        st.info("Waiting for alerts...")